from __future__ import annotations

from pathlib import Path


GENERATED = "Generated by agent_orchestra_minimal.launch_material."
HOOK_COMMAND = "python3 $CODEX_HOME/hooks/agent_orchestra_stop_hook.py"
# Codex 0.132.0 trust hash for HOOK_COMMAND. The state key still uses each
# generated config path, but this hash remains stable because the command is stable.
HOOK_TRUSTED_HASH = "sha256:15aa200b589589dbf1aa39731c5360abf465ca6e1a9a0671d16eada7320259d4"


def codex_config(workspace: Path, config_path: Path) -> str:
    return f"""# {GENERATED}
[projects."{workspace}"]
trust_level = "trusted"

[[hooks.Stop]]
[[hooks.Stop.hooks]]
type = "command"
command = "{HOOK_COMMAND}"
timeout = 5

[hooks.state]

[hooks.state."{config_path}:stop:0:0"]
trusted_hash = "{HOOK_TRUSTED_HASH}"
"""
