from __future__ import annotations

import os
import re
import ast
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Mapping

try:
    import tomllib
except ModuleNotFoundError:  # pragma: no cover - exercised on Python < 3.11
    tomllib = None  # type: ignore[assignment]


GENERATED = "Generated by agent_orchestra_minimal.launch_material."
HOOK_COMMAND = "python3 $CODEX_HOME/hooks/agent_orchestra_stop_hook.py"
# Codex 0.132.0 trust hash for HOOK_COMMAND. The state key still uses each
# generated config path, but this hash remains stable because the command is stable.
HOOK_TRUSTED_HASH = "sha256:15aa200b589589dbf1aa39731c5360abf465ca6e1a9a0671d16eada7320259d4"
DISABLE_MCP_INHERITANCE_ENV = "AGENT_ORCHESTRA_DISABLE_MCP_INHERITANCE"
MCP_SOURCE_CONFIG_ENV = "AGENT_ORCHESTRA_MCP_SOURCE_CONFIG"
DEFAULT_MCP_STARTUP_TIMEOUT_SEC = 30
SAFE_TOML_KEY = re.compile(r"^[A-Za-z0-9_-]+$")


def codex_config(workspace: Path, config_path: Path) -> str:
    workspace_key = _toml_basic_string(str(workspace))
    state_key = _toml_basic_string(f"{config_path}:stop:0:0")
    mcp = inspect_mcp_inheritance()
    config = f"""# {GENERATED}
[projects.{workspace_key}]
trust_level = "trusted"

[[hooks.Stop]]
[[hooks.Stop.hooks]]
type = "command"
command = "{HOOK_COMMAND}"
timeout = 5

[hooks.state]

[hooks.state.{state_key}]
trusted_hash = "{HOOK_TRUSTED_HASH}"
"""
    if mcp.config_text:
        config += "\n" + mcp.config_text
    return config


@dataclass(frozen=True)
class McpInheritance:
    enabled: bool
    source_config: Path | None
    servers: tuple[str, ...]
    config_text: str
    error: str | None = None
    playwright_detected: bool = False

    @property
    def playwright_present(self) -> bool:
        return self.playwright_detected or any("playwright" in name.casefold() for name in self.servers)


def inspect_mcp_inheritance(source_config: str | Path | None = None) -> McpInheritance:
    if os.environ.get(DISABLE_MCP_INHERITANCE_ENV) == "1":
        return McpInheritance(False, None, (), "")
    source = Path(source_config).expanduser() if source_config else _mcp_source_config()
    if source is None:
        return McpInheritance(True, None, (), "")
    try:
        payload = _load_toml(source)
    except (OSError, ValueError) as exc:
        return McpInheritance(True, source, (), "", str(exc))
    raw_servers = payload.get("mcp_servers", {})
    if not isinstance(raw_servers, dict):
        return McpInheritance(True, source, (), "", "mcp_servers is not a table")
    servers = tuple(sorted(str(name) for name in raw_servers))
    text = _mcp_servers_toml(raw_servers, servers)
    playwright = any(_mentions_playwright(name, raw_servers.get(name)) for name in servers)
    return McpInheritance(True, source, servers, text, playwright_detected=playwright)


def mcp_command_by_server(source_config: str | Path | None = None) -> dict[str, str]:
    source = Path(source_config).expanduser() if source_config else _mcp_source_config()
    if source is None or os.environ.get(DISABLE_MCP_INHERITANCE_ENV) == "1":
        return {}
    try:
        payload = _load_toml(source)
    except (OSError, ValueError):
        return {}
    servers = payload.get("mcp_servers", {})
    if not isinstance(servers, dict):
        return {}
    commands: dict[str, str] = {}
    for name, data in servers.items():
        if isinstance(data, dict) and isinstance(data.get("command"), str):
            commands[str(name)] = str(data["command"])
    return commands


def _mcp_source_config() -> Path | None:
    candidates: list[Path] = []
    if source := os.environ.get(MCP_SOURCE_CONFIG_ENV):
        candidates.append(Path(source).expanduser())
    if codex_home := os.environ.get("CODEX_HOME"):
        candidates.append(Path(codex_home).expanduser() / "config.toml")
    candidates.append(Path.home() / ".codex" / "config.toml")
    return next((path for path in candidates if path.is_file()), None)


def _load_toml(path: Path) -> dict[str, Any]:
    text = path.read_text(encoding="utf-8")
    if tomllib is not None:
        return tomllib.loads(text)
    return _load_mcp_only_toml(text)


def _load_mcp_only_toml(text: str) -> dict[str, Any]:
    payload: dict[str, Any] = {"mcp_servers": {}}
    current: tuple[str, ...] | None = None
    for raw_line in text.splitlines():
        line = _strip_comment(raw_line).strip()
        if not line:
            continue
        if line.startswith("[[") and line.endswith("]]"):
            current = None
            continue
        if line.startswith("[") and line.endswith("]") and not line.startswith("[["):
            path = tuple(_parse_key(part) for part in _split_top_level(line[1:-1], "."))
            current = path if path[:1] == ("mcp_servers",) else None
            if current:
                _ensure_table(payload, current)
            continue
        if current and "=" in line:
            key, value = line.split("=", 1)
            _ensure_table(payload, current)[_parse_key(key.strip())] = _parse_value(value.strip())
    return payload


def _ensure_table(root: dict[str, Any], path: tuple[str, ...]) -> dict[str, Any]:
    table = root
    for part in path:
        child = table.setdefault(part, {})
        if not isinstance(child, dict):
            raise ValueError(f"TOML path {'.'.join(path)} is not a table")
        table = child
    return table


def _mcp_servers_toml(servers: Mapping[str, Any], names: tuple[str, ...]) -> str:
    lines = [f"# Inherited MCP servers: {', '.join(names) if names else '(none)'}"]
    for name in names:
        value = servers.get(name, {})
        if isinstance(value, dict):
            _append_toml_table(lines, ("mcp_servers", name), _bounded_mcp_server(value))
    return "\n".join(lines) + "\n" if names else ""


def _bounded_mcp_server(value: Mapping[str, Any]) -> dict[str, Any]:
    result = dict(value)
    if "command" in result:
        timeout = result.get("startup_timeout_sec")
        if not isinstance(timeout, int) or timeout < 1 or timeout > DEFAULT_MCP_STARTUP_TIMEOUT_SEC:
            result["startup_timeout_sec"] = DEFAULT_MCP_STARTUP_TIMEOUT_SEC
    return result


def _mentions_playwright(name: str, value: Any) -> bool:
    if "playwright" in name.casefold():
        return True
    if isinstance(value, str):
        return "playwright" in value.casefold()
    if isinstance(value, list):
        return any(_mentions_playwright("", item) for item in value)
    if isinstance(value, dict):
        return any(
            key in {"command", "args"} and _mentions_playwright("", item)
            for key, item in value.items()
        )
    return False


def _strip_comment(line: str) -> str:
    in_quote = False
    escape = False
    for index, char in enumerate(line):
        if escape:
            escape = False
            continue
        if char == "\\" and in_quote:
            escape = True
            continue
        if char == '"':
            in_quote = not in_quote
        if char == "#" and not in_quote:
            return line[:index]
    return line


def _parse_key(value: str) -> str:
    value = value.strip()
    if value.startswith('"') and value.endswith('"'):
        return str(ast.literal_eval(value))
    return value


def _parse_value(value: str) -> Any:
    if value.startswith(('"', "'")):
        return ast.literal_eval(value)
    if value in {"true", "false"}:
        return value == "true"
    if value.startswith("[") and value.endswith("]"):
        inner = value[1:-1].strip()
        return [] if not inner else [_parse_value(part.strip()) for part in _split_top_level(inner, ",")]
    if value.startswith("{") and value.endswith("}"):
        result: dict[str, Any] = {}
        for part in _split_top_level(value[1:-1], ","):
            key, raw, item = part.partition("=")
            if raw:
                result[_parse_key(key.strip())] = _parse_value(item.strip())
        return result
    try:
        return int(value)
    except ValueError:
        return value


def _split_top_level(value: str, separator: str) -> list[str]:
    parts: list[str] = []
    start = depth = 0
    in_quote = escape = False
    for index, char in enumerate(value):
        if escape:
            escape = False
        elif char == "\\" and in_quote:
            escape = True
        elif char == '"':
            in_quote = not in_quote
        elif not in_quote and char in "[{":
            depth += 1
        elif not in_quote and char in "]}":
            depth -= 1
        elif not in_quote and depth == 0 and char == separator:
            parts.append(value[start:index].strip())
            start = index + 1
    parts.append(value[start:].strip())
    return [part for part in parts if part]


def _append_toml_table(lines: list[str], path: tuple[str, ...], table: Mapping[str, Any]) -> None:
    lines.append("")
    lines.append(f"[{'.'.join(_toml_key(key) for key in path)}]")
    for key in sorted(table):
        value = table[key]
        if not isinstance(value, dict):
            lines.append(f"{_toml_key(str(key))} = {_toml_value(value)}")
    for key in sorted(table):
        value = table[key]
        if isinstance(value, dict):
            _append_toml_table(lines, (*path, str(key)), value)


def _toml_key(value: str) -> str:
    return value if SAFE_TOML_KEY.fullmatch(value) else _toml_basic_string(value)


def _toml_value(value: Any) -> str:
    if isinstance(value, str):
        return _toml_basic_string(value)
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return repr(value)
    if isinstance(value, list):
        return "[" + ", ".join(_toml_value(item) for item in value) + "]"
    if isinstance(value, dict):
        parts = [
            f"{_toml_key(str(key))} = {_toml_value(item)}"
            for key, item in sorted(value.items())
        ]
        return "{ " + ", ".join(parts) + " }"
    return _toml_basic_string(str(value))


def _toml_basic_string(value: str) -> str:
    escaped = (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\b", "\\b")
        .replace("\t", "\\t")
        .replace("\n", "\\n")
        .replace("\f", "\\f")
        .replace("\r", "\\r")
    )
    return f'"{escaped}"'
