from __future__ import annotations

import json
import shlex
from pathlib import Path


GENERATED = "Generated by agent_orchestra_minimal.launch_material."
# bypassPermissions is the default. The orchestrated team must edit the target
# repo — including dot-directories like `.claude/` — and run shell commands fully
# unattended, and no scoped permission allow-list reliably covers that: a bare
# edit allow rule is inert, and a path-glob allow rule (`Edit(//target/**)`) misses
# dot-directories, so the team stalls on the first `.claude/...` edit. Disabling
# approval (bypassPermissions) removes the whole class of permission prompts in one
# move. The cost is a one-time "Bypass Permissions" launch warning gate (the trust
# seed does not suppress it), which the operator/launch skill accepts with a single
# keystroke after each launch. This is looser than the Codex posture, which paired
# `--ask-for-approval never` with `--sandbox workspace-write` (write confinement):
# bypassPermissions has no sandbox, so isolation rests on the isolated HOME /
# CLAUDE_CONFIG_DIR / `--add-dir` scoping plus the operator's accepted risk.
# acceptEdits stays available via AGENT_ORCHESTRA_PERMISSION_MODE for operators who
# want per-action approval, but it only auto-accepts edits inside the cwd workspace,
# so it is not unattended for target edits.
DEFAULT_PERMISSION_MODE = "bypassPermissions"


def claude_settings(hook_path: Path, *, permission_mode: str = DEFAULT_PERMISSION_MODE) -> str:
    """Render the isolated Claude Code ``settings.json``.

    Claude Code has no per-hash hook trust model, so this replaces the Codex
    ``agent-orchestra.config.toml`` with a plain settings file that registers the
    Stop Hook and sets the permission mode. The hook command embeds an absolute,
    shell-quoted path so it does not depend on ``$CLAUDE_CONFIG_DIR`` expansion at
    hook run time.
    """

    command = f"python3 {shlex.quote(str(hook_path))}"
    settings = {
        "hooks": {
            "Stop": [
                {"hooks": [{"type": "command", "command": command}]},
            ],
        },
        "permissions": {"defaultMode": permission_mode},
    }
    return _dump(settings)


def trust_seed(workspace: Path) -> str:
    """Render a ``.claude.json`` that pre-accepts the workspace trust dialog.

    Claude Code stops at a per-directory trust prompt for any untrusted folder,
    which blocks unattended launch. Pre-seeding the trust disposition is the
    Claude Code analog of the Codex ``trust_level = "trusted"`` project entry.
    """

    seed = {
        "hasCompletedOnboarding": True,
        "projects": {
            str(workspace): {
                "hasTrustDialogAccepted": True,
                "hasCompletedProjectOnboarding": True,
                "projectOnboardingSeenCount": 1,
                "allowedTools": [],
            }
        },
    }
    return _dump(seed)


def _dump(data: object) -> str:
    return json.dumps(data, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
